// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 10.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Core
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    #line 1 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class POJO : T4Base
    {
        public override string TransformText()
        {
            this.Write("package ");
            
            #line 6 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Namespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nimport java.sql.Date;\r\nimport java.sql.Timestamp;\r\n\r\npublic class ");
            
            #line 11 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TableName));
            
            #line default
            #line hidden
            this.Write(" {\r\n\t");
            
            #line 12 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
foreach(var column in this.DbColumns){ 
            
            #line default
            #line hidden
            this.Write("\r\n\t/**\r\n\t*");
            
            #line 15 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Remark));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\tprivate ");
            
            #line 17 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.JavaType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 17 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t");
            
            #line 18 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t");
            
            #line 21 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
foreach(var column in this.DbColumns){ 
            
            #line default
            #line hidden
            this.Write("\r\n\t/**\r\n\t*");
            
            #line 24 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Remark));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\tpublic ");
            
            #line 26 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.JavaType));
            
            #line default
            #line hidden
            this.Write(" get");
            
            #line 26 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName.ToTitleUpper()));
            
            #line default
            #line hidden
            this.Write("(){\r\n\t\treturn this.");
            
            #line 27 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write(";\r\n\t}\r\n\r\n\t/**\r\n\t*");
            
            #line 31 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Remark));
            
            #line default
            #line hidden
            this.Write("\r\n\t*/\r\n\tpublic void set");
            
            #line 33 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName.ToTitleUpper()));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 33 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.JavaType));
            
            #line default
            #line hidden
            this.Write("  value) {\r\n\t\tthis.");
            
            #line 34 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write(" = value;\r\n\t}\r\n\t");
            
            #line 36 "D:\GitHub\CodeGenerator\CodeGenerator\Core\POJO.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
