// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 12.0.0.0
//  
//     对此文件的更改可能会导致不正确的行为。此外，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Core
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public partial class POCO : T4Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\n\r\nnamespace ");
            
            #line 8 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic class ");
            
            #line 10 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TableName));
            
            #line default
            #line hidden
            this.Write(" \r\n\t{\r\n\t\t");
            
            #line 12 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
foreach(var column in this.DbColumns){ 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t/// <summary>\r\n        /// ");
            
            #line 15 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.Remark));
            
            #line default
            #line hidden
            this.Write("\r\n        /// </summary>\r\n\t\tpublic ");
            
            #line 17 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 17 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(column.ColumnName));
            
            #line default
            #line hidden
            this.Write("{ get; set; }\r\n\t\t");
            
            #line 18 "D:\GitHub\CodeGenerator\CodeGenerator.Core\POCO.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
